### ISSUE TITLE
Partitioned on Athena

### ISSUE THREAD

**Issue by JosefinaArayaTapia** [klescosia/aws-glue-delta-lake#1]
When doing the partitioning in athena i get a duplication error.
@klescosia 

[https://i.imgur.com/vNs3FXo.png](https://i.imgur.com/vNs3FXo.png)

Thanks

**Comment by klescosia** [comment]
Hi! You don't need to add the `partition` column in the `table definition`. You just specify it using the `PARTITIONED BY` settings.

**Comment by JosefinaArayaTapia** [comment]
The solution was to create the partition when saving the delta:

`new_data_DF.write.format("delta").partitionBy("PERIODO").save("dbfs:/mnt/main/sales")`

Thanks

**Comment by klescosia** [comment]
Yeah, that'll work too. Cool!
