### ISSUE TITLE
AnalysisException: cannot resolve '`name.email`' given input columns

### ISSUE THREAD

**Issue by heetu** [klescosia/aws-glue-delta-lake#2]
Edit: my error is automatic convert into GitHub text format so I am adding an error pic here.

![image](https://user-images.githubusercontent.com/34266111/165746657-a1bbbfec-f804-4bc7-bdc7-a9072acda67d.png)

I was going through this whole file and I found there is filed email same as same what is used in the upsert file can you please help me to resolve these issues.

If you need more details just let me know.

Thank You,
Heet

**Comment by klescosia** [comment]
Hi Heet,

Can you double check in your dataset if you have an "email" column present?
Or if you can list down the column names.

Because I think "email" is not included in your dataset that's why it's
throwing this error/exception.

--
Kyle

**Comment by heetu** [comment]
Hello @klescosia,

Thank you quick reply.

Let me upload a pic here
![image](https://user-images.githubusercontent.com/34266111/165766040-4547bbc3-8c87-43b9-92c3-22aec836245d.png)

You can see the list of my dataset column. The field email is there.

**Comment by klescosia** [comment]
Okay. Is it possible for you to share your query?

**Comment by heetu** [comment]
Sure, Here it is.

![image](https://user-images.githubusercontent.com/34266111/165887933-6ca87125-ef55-4165-8d26-1abcb174b030.png)

**Comment by klescosia** [comment]
Okay, then the list of columns in the dataset? May I also ask?

**Comment by heetu** [comment]
Sure I will share here, but let me dig into the first late me read some essential documents of the delata-lake and spark configuration; I will update here once I find something.

**Comment by klescosia** [comment]
Yeah sure, because I think it's not detecting the column that you are
referring to.

**Comment by heetu** [comment]
Hey @klescosia,

I figured out where the problem was. I am using an extra spark configuration that was not suitable for delta configuration, so it's creating issues.
In conclusion, please read all the spark configurations doc. Before use, if you are using an extra spark configuration, check if it will create any impact or not with your delta lake configuration.

**Comment by klescosia** [comment]
Awesome! Glad that you were able to figure it out. Thanks for the tip also!
